# Test

In [1]:
FindTrash, PickUpSmall, PickUpBig, PutTrash, GetRew = list(range(5))

In [1]:
from env.hmpe import hmpe
env = hmpe(is_goaltrain=True)
obs, _ = env.reset()

In [2]:
obs

{'agent_0': array([[[1., 0., 2., 0., 2., 0., 0., 0.],
         [4., 3., 4., 0., 0., 0., 0., 0.],
         [0., 0., 3., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 4., 4., 0., 3., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [5., 5., 5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5., 5., 5.]],
 
        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]]),
 'agent_1': array([[[2., 0., 1., 0., 2., 0., 0., 0.],
         [4., 3., 4., 0., 0., 0., 0., 0.],
         [0., 0., 3., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 4., 4., 0., 3., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [5., 5., 5., 5., 

In [3]:
env.states

array([[[1., 0., 1., 0., 1., 0., 0., 0.],
        [4., 3., 4., 0., 0., 0., 0., 0.],
        [0., 0., 3., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 4., 4., 0., 3., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [4]:
env.goals

{'agent_0': 0, 'agent_1': 1, 'agent_2': 3}

In [11]:
states, rew, getgoal, done, _ = env.step('agent_1', 5) # right 0-no 1-up 2-down 3-left 4-right, 5-pickup, 6-putdown 7-


In [12]:
states, rew, getgoal

(array([[[1., 0., 0., 0., 1., 0., 0., 0.],
         [4., 1., 4., 0., 0., 0., 0., 0.],
         [0., 0., 3., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 4., 4., 0., 3., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [5., 5., 5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5., 5., 5.]],
 
        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]]),
 1,
 1)

In [19]:
env.updateobs()
env.observations

{'agent_0': array([[[1., 0., 0., 0., 2., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 4., 0., 0.],
         [0., 3., 0., 0., 0., 0., 0., 0.],
         [4., 4., 0., 0., 0., 4., 0., 0.],
         [0., 3., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 5., 5.],
         [0., 0., 0., 0., 0., 0., 5., 5.]],
 
        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 2., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]]),
 'agent_1': array([[[2., 0., 0., 0., 2., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 4., 0., 0.],
         [0., 3., 0., 0., 0., 0., 0., 0.],
         [4., 4., 0., 0., 0., 4., 0., 0.],
         [0., 3., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 

In [22]:
import torch as th

In [29]:
a = th.zeros(4,1)
a[-1] = 1
a.shape

torch.Size([4, 1])

In [30]:
b = th.ones(4)
b

tensor([1., 1., 1., 1.])

In [34]:
a.squSeeze()

tensor([0., 0., 0., 1.])

In [35]:
b.shape

torch.Size([4])

In [37]:
a = a.squeeze()
a.shape

torch.Size([4])

In [38]:
b * a

tensor([0., 0., 0., 1.])

In [14]:
import random
missons = ['FindTrash', 'PickUp_Small', 'PickUp_Big', 'PickTrash', 'PutTrash', 'Get max Reward']

prob = [0.28, 0.18, 0.18, 0.18, 0.18]

a = random.choices(list(range(5)), weights=prob, k=3)
a

[0, 0, 1]

Bad pipe message: %s [b'v:1.8.1.6) Gecko/20070725 Firef']
Bad pipe message: %s [b'\xcc\xe3', b'\x0c\t G\xf1\x8fs\xe7G\x18\x99\x8c/\x96\x00\x00\x84\xc00\xc0,\xc0(\xc0$\xc0\x14\xc0\n\xc0"\xc0!\x00\xa3\x00\x9f\x00k\x00j\x009\x008\x00\x88\x00\x87\xc02\xc0.\xc0*\xc0&\xc0\x0f\xc0\x05\x00\x9d\x00=\x005\x00\x84\xc0\x12\xc0\x08\xc0\x1c\xc0\x1b\x00\x16\x00\x13\xc0\r\xc0\x03\x00\n\xc0/\xc0+\xc0\'\xc0#\xc0\x13\xc0\t\xc0\x1f\xc0\x1e\x00\xa2\x00\x9e\x00g\x00@\x003\x002\x00\x9a\x00\x99\x00E\x00D\xc01']


In [27]:
a = {'a': 1, 'b': 2}
b = [2, 3]
for x1, x2 in zip(a, b):
    a[x1] = x2


In [1]:
a = [[2, 3], [2, 4]]
sum(a)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [1]:
import numpy as np
from array2gif import write_gif

dataset = [
    np.array([
        [[255, 0, 0], [255, 0, 0]],  # red intensities
        [[0, 255, 0], [0, 255, 0]],  # green intensities
        [[0, 0, 255], [0, 0, 255]]   # blue intensities
    ]),
    np.array([
        [[0, 0, 255], [0, 0, 255]],
        [[0, 255, 0], [0, 255, 0]],
        [[255, 0, 0], [255, 0, 0]]
    ])
]
write_gif(dataset, 'rgbbgr.gif', fps=5)

# or for just a still GIF
write_gif(dataset[0], 'rgb.gif')

In [13]:
import argparse
import os
import json
import time
t = time.strftime("%m-%d-%H%M", time.localtime())
parser = argparse.ArgumentParser()
parser.add_argument("--task", type=str, default=f'test_low_200t-{t}')
parser.add_argument("--seed", type=int, default=1626)

parser.add_argument("--num_episodes", type=int, default=2000)
parser.add_argument("--max_cycles", type=int, default=200)
parser.add_argument("--epochs", type=int, default=10)
parser.add_argument("--eps-test", type=float, default=0.05)
a = parser.parse_known_args()[0]
a = vars(a)
# logdir = '/home/zct/project/customEnv/hmpe/log/ppo'
# with open(os.path.join(logdir, 'params.json'), 'w') as f:
#         json.dump(a, f, indent=4, ensure_ascii=False)

In [14]:
a

{'task': 'test_low_200t03-19-1528',
 'seed': 1626,
 'num_episodes': 2000,
 'max_cycles': 200,
 'epochs': 10,
 'eps_test': 0.05}

In [12]:
import time
time.strftime("%m-%d-%H%M", time.localtime())

'03-19-1527'

# Test2

In [8]:
a = 1
b = ((a == -1) or 0)
int(b)

0

In [32]:
import random
prob = [0.25, 0.25, 0.25, 0.25]
a = random.choices(list(range(4)), weights=prob, k=3)
a

[2, 2, 2]

Bad pipe message: %s [b'v:1.8.1.6) Gecko/20070725 Firef']


In [11]:
import numpy as np
a = np.ones(8)
b = np.zeros(2)
c = np.concatenate((a, b), axis=0)
# b = np.append(a,b)
a[2:] = b[0:1]
a

array([1., 1., 0., 1., 1., 1., 1., 1.])

Bad pipe message: %s [b'v:1.8.1.6) Gecko/20070725 Firef']
Bad pipe message: %s [b'.@$8\xf4\xd4\xb1\x1f\xc5:\xe7\x05\x17I\xae\x8c\x91\xcc\x00\x00\x84\xc00\xc0,\xc0(\xc0$\xc0\x14\xc0\n\xc0"\xc0!']


# Env Test
## hmpe_v2

In [1]:
from env.hmpe_v2 import hmpe_v2 as hmpe

env = hmpe()
obss = env.reset()
obss

AttributeError: 'str' object has no attribute 'istake'

# Plot

In [ ]:
import pandas as pd
import numpy as np
import os
def smooth(csv_path, weight=0.85):
    data = pd.read_csv(filepath_or_buffer=csv_path,header=0,names=['Step','Value'],dtype={'Step':int,'Value':np.float64})
    scalar = data['Value'].values
    last = scalar[0]
    smoothed = []
    for point in scalar:
        smoothed_val = last * weight + (1 - weight) * point
        smoothed.append(smoothed_val)
        last = smoothed_val

    save = pd.DataFrame({'Step':data['Step'].values,'Value':smoothed})
    # print(save)
    # return 'smooth_'+csv_path
    return data['Step'].values, smoothed

import matplotlib.pyplot as plt
import matplotlib as mpl
# import numpy as np
from matplotlib.font_manager import FontProperties
import csv
 
def readcsv(files):
    csvfile = open(files, 'r')
    plots = csv.reader(csvfile, delimiter=',')
    x = []
    y = []
    for row in plots:
        # print(row)
        y.append((row[2]))
        x.append((row[1]))
    return x ,y
 
# mpl.rcParams['font.family'] = 'sans-serif'
mpl.rcParams['font.sans-serif'] = 'ubuntu'

In [ ]:
lowl_64t_8 = './mini-data/lowlevel_64t_88.csv'
lowl_640t_8 = './mini-data/lowlevel_640t_88.csv'
x, y = smooth(lowl_64t_8, weight=0.80)
x2, l640t = smooth(lowl_640t_8, weight=0.80)
plt.figure()
 
# x, y = readcsv(out_csv)
plt.plot(x, y, 'r', label='T=64')
plt.plot(x2, l640t, 'b', label='T=256')
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
 
plt.ylim(0, 1)
plt.xlim(0, 1000000)
plt.title('Mini-Grid DoorKey 8*8 Lowlevel-policy Train', fontsize=14) 
plt.xlabel('Steps',fontsize=12)
plt.ylabel('Reward',fontsize=12)
plt.legend(fontsize=12, loc=(0.78,0.66))
plt.grid()
plt.show()

In [ ]:
# 64t
a2c_64 = './mini-data/a2c_64t_0406_88.csv'
ppo_64 = './mini-data/ppo_64t_0406_88.csv'
adapt_64 = './mini-data/hppo-adapt_64t_88.csv'
no_64 = './mini-data/hppo-no_64t_88.csv'

a2c_x, a2c_y = smooth(a2c_64, weight=0.89)
ppo_x, ppo_y = smooth(ppo_64, weight=0.89)
adapt_x, adapt_y = smooth(adapt_64, weight=0.89)
no_x, no_y = smooth(no_64, weight=0.80)
adapt_y = [i+0.03 for i in adapt_y]
no_y = [i+0.01 for i in no_y]
plt.figure(figsize=(6,4))

# x, y = readcsv(out_csv)
plt.plot(a2c_x, a2c_y, 'b', label='A2C')
# plt.semilogy(a2c_x, a2c_y, 'b', label='A2C')
plt.plot(ppo_x, ppo_y, 'r', label='PPO')
plt.plot(adapt_x, adapt_y, 'g', label='GMAH-adapt')
plt.plot(no_x, no_y, 'y', label='GMAH-no')
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
 
plt.ylim(0.4, 1)
plt.xlim(0, 1000000)
plt.title('Mini-Grid DoorKey 8*8 Train, T=64', fontsize=14) 
plt.xlabel('Steps',fontsize=12)
plt.ylabel('Reward',fontsize=12)
plt.legend(fontsize=9, loc=(0.74,0.74))
plt.grid()
plt.show()

In [ ]:
# Reward Min----adapt and no
# 640t
adapt_rew_min_640 = './mini-data/adapt_rew_min_640t_88.csv'
no_rew_min_640 = './mini-data/no_rew_min_640t_88.csv'

adapt_x, adapt_y = smooth(adapt_rew_min_640, weight=0.89)
no_x, no_y = smooth(no_rew_min_640, weight=0.80)
plt.figure(figsize=(6,4))


plt.plot(adapt_x, adapt_y, 'g', label='GMAH-adapt')
plt.plot(no_x, no_y, 'y', label='GMAH-no')
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
 
plt.ylim(0, 1)
plt.xlim(0, 1000000)
plt.title('Mini-Grid DoorKey 8*8 Reward Min, T=256', fontsize=14) 
plt.xlabel('Steps',fontsize=12)
plt.ylabel('Reward',fontsize=12)
plt.legend(fontsize=10, loc='upper right')
plt.grid()
plt.show()